### ISSUE TITLE
AppMan as an AppImage?

### ISSUE THREAD

**Issue by probonopd** [ivan-hc/AppMan#1]
Hello @ivan-hc, will AppMan be downloadable as an AppImage? Thanks.

**Comment by ivan-hc** [comment]
Hi, I'm planning to made an AppImage for it in the future, but being a bash script that contains all the instructions for each app of this repository (that for the moment are less than 40) I should improve it before, and finding a way to merge the istructions for each app (about, remove and install). Pratically AppMan must become completelly independent from the name of each programm (for all the aliases, for example firefox-stable|firefox, freeCAD-mamba|freecad|freeCAD, google-chrome|chrome, etcetera...). Until then, I must add new lines to the main script.

**Comment by probonopd** [comment]
Thank you very much. Looking forward to it! :+1:

**Comment by ivan-hc** [comment]
Hi again, AppMan now is ready, but being a script that calls other scripts into a /opt/bin folder to be created and being many script depending on your tools (pkg2appimage, appimagetool and appimageupdatetool) as described in the [installation guide](https://github.com/ivan-hc/AppMan#installation), creating an AppImage for it seems to be useless.

All I suggest now is to create recipes using [my scripts](https://github.com/ivan-hc/AppMan/tree/main/models). As you can read from them, they are a mix between your pkg2appimage recipes with the support of appimagetool (and appimageupdate, where the developer have a non-generic link for its updatable AppImage, for example in [Audacity, at the line 6](https://github.com/ivan-hc/AppMan/blob/main/applications/audacity/audacity-installer)).

The final result is an AppImage in /opt/bin with the icon and the full launcher (or launchers, see Libreoffice Still/Fresh) installable with the command `appman -i [program]` and removable with `appman -r [program]`.

Today I've also updated the [requirements for an application to upload](https://github.com/ivan-hc/AppMan#how-to-prepare-an-application---structure) and tried to upload other "recipes" for this repository. With these guidelines an user have not much to do but trying the precompilated script with its customizations before him made a pull request.

I've also prepared a [basic sample of appimage](https://github.com/ivan-hc/appimage-sample) into another repository if this could help someone. There are a lot of applications from AUR we can use on Debian-based too using tools like AppMan... but my main problem is really "stupid": to download packages from a link that contains numbers. They can be variable and the final product requires updating the script each time. I'd like to prevent this. If many developers continue to put many versions into one link (that's why I've not uploaded GIMP AppImage) or many new versions in different links, I can't provide the last release for all. Once I've found a solution, I can create new models of scripts for AppMan.

All I'd like to do is to made AppImages ready to use, easy to install and easy to prepare for all the users. Maybe one day I will create another script for this, if I have time enough for this. This is just an hobby for me, I'm not a real expert or a developer, but AppImages have fashinated me. They made me think that we can really try to merge all the linux distributions and stop fighting each other for Debian or Arch. Is this continuous division that takes linux longer from the masses. Maybe using standalone apps (and a centralizate repository) we can really made the difference.

Sorry for my long talking, but for me is an honor to be contacted by the father of standalone apps on linux. I wanted to take this opportunity to thank you.

**Comment by probonopd** [comment]
Thanks @ivan-hc, added it to https://github.com/AppImage/awesome-appimage#package-managers.

**Comment by ivan-hc** [comment]
hi, I've just created an AppImage for AppMan (x86_64)
