### ISSUE TITLE
Workaround?

### ISSUE THREAD

**Issue by psython123** [ivan-hc/AppMan#14]
If you do not meet the requirements and you do not have sudo access, there is no workaround to use it anyways, correct? I get the following error trying to initiate the script:

"ERROR: ar not found, required by some installation scripts.

ERROR: curl not found, required by some installation scripts.

ERROR: zsync not found, required by some installation scripts."

**Comment by ivan-hc** [comment]
AppMan is only a script/text file, edit the line 34

```
for name in "ar" "cat" "chmod" "chown" "curl" "grep" "sed" "tar" "unzip" "wget" "zsync"; do
```
this way
```
for name in "cat" "chmod" "chown" "grep" "sed" "tar" "unzip" "wget"; do
```

NOTE, the sense of these dependences you don't have is:

- `curl` is used from many installation scripts (about 30-40% of them) to check the download URLs if a page have a different kind of APIs;
- `zsync` is needed to update some Appimages (about 10% of them), you wont be able to update them;
- `ar` is the only one optional (it is included in `binutils`) and it is used by one of these scripts because it is needed to extract .deb packages (I had a lot of .deb package to manage before I started converting them to AppImages by myself).

**Comment by ivan-hc** [comment]
To be more specific:

> `curl` is used from many installation scripts to check the download URLs if a page have a different kind of APIs;

52 installation scripts, 18 for x86_64, 10 for aarch64 and the others for i686 

> `zsync` is needed to update some Appimages, you wont be able to update them;

229 installation scripts for x86_64

> `ar` is the only one optional (it is included in `binutils`) and it is used by one of these scripts because it is needed to extract .deb packages (I had a lot of .deb package to manage before I started converting them to AppImages by myself).

14 installation scripts, 1 for x86_64, 3 for aarch64 and 1 for i686
