### ISSUE TITLE
re: AppMan: restrict ~/.profile's patch to those who need it

### ISSUE THREAD

**Issue by shlozm** [ivan-hc/AppMan#27]
I just installed Debian on a laptop, this time with a XFCE and lightdm login manager. I noticed .profile did not get sourced (probably because I wasn't logging in through tty) and .local/bin was not on my $PATH at all.
I installed appman and a few appimages including gimp, appman added the 2 lines to my .bashrc but did not edit .profile because my $PATH didn't have .local/bin in the beginning as per the latest fix.
echo $PATH showed .local/bin at the end as per .bashrc, BUT gimp would not run!
After commenting out the lines in .profile gimp ran!
I think the Archimage is sourcing .profile even if the system locally is not.
Once I commented out the lines in .profile I even tested changing the order of $PATH in .bashrc to put .local/bin first and gimp still ran. That shows that the Archimage doesn't care about .bashrc only about .profile.

Can you test on your system? 
Do the following:
Download gimp appimage somewhere in $HOME (such as ~/Downloads)
touch ~/.local/bin/gimp
chmod +x ~/.local/bin/gimp
Then, try to run gimp appimage that you downloaded (even without renaming) 
I'm pretty sure it won't run

The fix is to edit Debian default .profile always like before.

**Comment by ivan-hc** [comment]
At this point I need to find a way to notify the user of the latest CLI commit, to let them know what the heck I'm doing with each update/downgrade. I'll probably add a message to "-s", I don't want to seem crazy.

**Comment by ivan-hc** [comment]
@shlozm I've updated all my ArchImage's build scripts by changing the internal AppRun like this, from
```
export PATH=$HERE/.local/share/junest/bin/:$PATH
```
to
```
export PATH=$PATH:$HERE/.local/share/junest/bin
```
I hope this will give to the ArchImages the right priority in $PATH, but to see if something is changed we need to wait the next releases (GIMP is updated each Sunday while GIMP GIT is daily, like OBS Studio, etcetera...).

I'm bored of updating everyone manually right now, also because here it's almost 6 in the morning and I haven't slept yet.
