### ISSUE TITLE
Installation Script Clears Error Messages Before Configuration

### ISSUE THREAD

**Issue by nazdridoy** [ivan-hc/AppMan#28]
**Description:**

After the installation script reaches the "◆ RUNNING THE INSTALLATION SCRIPT FOR" step, all error messages are getting cleared out before reaching the "◆ CONFIGURING "***" " step. This makes it challenging for users to diagnose installation issues and understand what went wrong.

**Problem:**

The stderr messages are being cleared out, and users are unable to read error messages generated during the installation process, hindering proper diagnosis of installation problems.

**Suggestion:**

It is recommended to modify the installation script so that stderr messages are not cleared out before reaching the "◆ CONFIGURING "***"" step. This will enable users to identify and troubleshoot issues during the installation process more effectively.

**Steps to Reproduce:**
1. Execute the installation script.
2. Observe that error messages generated during the installation process are cleared out before reaching the "◆ CONFIGURING "***"" step.

**Expected Behavior:**

Error messages should be retained and displayed to users even after the "◆ RUNNING THE INSTALLATION SCRIPT FOR" step, allowing for proper diagnosis of any installation issues.

**Environment:**
- Operating System: Archlinux
- Shell: ZSH
- Version of the application: 5.3.1-5

**Additional Information:**
![2024-01-18_16-05](https://github.com/ivan-hc/AppMan/assets/45564804/9064399c-e409-41b7-bc51-b83539c1fdd3)

**Comment by ivan-hc** [comment]
Hi, thank you for your detailed request, but there are reasons about my choice.

Can you see that message `mv: cannot stat squashfs-root...` ... etcetera? This is because the scripts to install the AppImages are quite similar between them, so the template is wrote to check and extract icons and .desktop files from the AppImage, wherever it is stored.

Being the structure of all AppImages quite different from a program to another, I need to speedup the check, and to do this I must scan the whole structure of the AppImage looking for what we need to integrate it into the system.

So the installed package has a specific way to be installed, it is not a PKGBUILD from AUR, we don't need to compile anything... and the purpose of using `less` in the `install` option is to make the installation output cleaner and more pleasant for most users.

Furthermore, my scripts are designed to be installed even without CLI, with "AppMan" you can use the `appman convert $APP` command to download the script from the "AM" repository and convert it to a local installer (which is what it does "AppMan", in fact), you make it executable and run it without root privileges, so you can see the output.

That said, if you have any doubts, use the `convert` command of "AppMan" and read what is written in the script.

In case some specific dependencies of some applications are missing (like `zsync`, `ar`, `unzip`...) there is a check in the CLI for that type of script that contains the keyword and you will receive the message "you cannot install the 'app without this dependency', or something like that.

If you prefer to install the app and see the outputs, use the `convert` option to get the desired script, and run it manually. "AppMan" is an interface, and with too many error messages that we are not interested in it is no longer beautiful. We don't care if the `mv` command didn't find the .desktop file in the AppImage root but in another folder, we only care that it is found and extracted.

I hope I have been clear and exhaustive enough.

**Comment by ivan-hc** [comment]
Line 887 https://github.com/ivan-hc/AM-Application-Manager/blob/5e0b3f354233883bb2a2852f2a27544bd580c5d5/APP-MANAGER#L887

Replace `$SUDOCOMMAND ./$arg | less -E` with `$SUDOCOMMAND ./$arg` to see all outputs.

**Comment by ivan-hc** [comment]
I'm just writing a new option `dev` or `developer` to enable/disable `| less -E`

**Comment by ivan-hc** [comment]
Second release in 4 hours: "AM"/AppMn 5.5

https://github.com/ivan-hc/AM-Application-Manager/releases/tag/5.5

you made me work hard today with your requests.
