### ISSUE TITLE
VirtualBox ?

### ISSUE THREAD

**Issue by in4matix** [ivan-hc/AppMan#34]
Hi Ivan,
Have you ever try to make VirtualBox Appimage? 
https://www.virtualbox.org/wiki/Linux_Downloads

**Comment by ivan-hc** [comment]
Sure, I've tried, but its not an easy task. Also GNOME Boxes, and [I have a repo for it](https://github.com/ivan-hc/Boxes-appimage)... but is quite impossible due to the kernel dependences (dkms and KVM modules), so if I try to run such a software, it crashes. Flatpak have done a good work with Boxes, but they use ostree to run their software and they have their layouts and runtimes as dependences.

Inthe case of Virtualbox, have you have seen, at boot, when the kernel loads Virtualbox modules? This is the reason because to create an AppImage for that is difficult... and I'm the first one that would see and use a Virtualbox AppImage, since it is my favourite virtualizzation software.

**Comment by in4matix** [comment]
I thought that much. Ah well, no harm in asking. My favorite is KVM / Qemu with Virtual Machine Manager (GUI).

**Comment by ivan-hc** [comment]
> I thought that much. Ah well, no harm in asking. My favorite is KVM / Qemu with Virtual Machine Manager (GUI).

I know that its ways better.... but I'm a newbie, and I had not less difficults in configuring it.

Also, I don't know how virtual disks are working there, I have a little SSD in my PC, and a great HDD for datas, so all'I've done is to symlink vitualbox configuration files and add the Virtualboc VMs directory on that HDD, so I can save space for the system. All my big files are stored there.

**Comment by in4matix** [comment]
I have the same setup. It is actually very easy to setup. See attached guide.
[Libvirt change default storage path.txt](https://github.com/ivan-hc/AppMan/files/15094005/Libvirt.change.default.storage.path.txt)

**Comment by ivan-hc** [comment]
thank you
