### ISSUE TITLE
aisleriot not working under appman

### ISSUE THREAD

**Issue by joedefen** [ivan-hc/AppMan#35]
- The .desktop file has "Exec=sol", but "sol" is not installed.  When I change the .desktop file to contain: "Exec=~/.local/bin/aisleriot", then it works.
- When it runs, however (and I don't if this is a problem to fix), then the cursors are relatively tiny, especially the card movement pointer (which turns into a very teeny "hand" cursor).  Anyhow, I've never seen any aisleriot deployment with such small cursors ... in this case, the hand is practically invisible on my laptop screen.

BTW, there are several apps that, for me, would be nice to have (as they are hand managed outliers in my kubuntu install), namely:

- copyq, efiboots, SeaMonkey, and veracrypt.  All but [efiboots](https://github.com/Elinvention/efiboots) are in the Arch/AUR repos.

I've tried to roll my own with "ArchImage", but that path has been nothing but frustration. Perhaps, these apps are "bad apples" in some way?  If there is a "wishlist", then perhaps they could go on that?

**Comment by ivan-hc** [comment]
I see more than one issues here, for three different repositories, "[AM](https://github.com/ivan-hc/AM)" (or this one, AppMan, they are the same), [Aisleriot-appimage](https://github.com/ivan-hc/Aisleriot-appimage) and [Archimage](https://github.com/ivan-hc/ArchImage):
1. Just fixed Aisleriot .desktop file https://github.com/ivan-hc/AM/commit/5abc4a1cf25cbe716418cf0d933430bb817aed0d , now you can install it without problems.
2. About Aisleriot AppImage, and cursors, this is because I've not included themes into the AppImage. Also if I'm the developer,  you should open the issue in the related repo https://github.com/ivan-hc/Aisleriot-appimage so if someone else have issues or want to collab to improve the AppImage, it knows where to start searching.
3. About "Archimage", this is not a magic tool to solve all problems and to build AppImages is not an easy task. I'm the developer and I have issues too with my creations. I'd like you see the last two I've solved for the same Archimage in the latest 24 hours... and after one month they where opened, https://github.com/ivan-hc/KDE-games-suite-appimage/issues/4 and https://github.com/ivan-hc/KDE-games-suite-appimage/issues/3
4. About "wishlists", I've 60 repos with 70+ AppImages. This is why I no more create new Appimages. I have too many to maintain.
5. About difficults in built AppImages, I've seen you have some Python projects among your repos. I don't use Python and I try to keep myself far from it, but i can't, since I have many problematic AppImages depending on Python, so I try and try again until I don't reach my goal. See again the search I've done in adding Kajongg to my kdegames appimage https://github.com/ivan-hc/KDE-games-suite-appimage/issues/3 , so never say never.

So the point 2 is the only one we can investigate on. Please open one at https://github.com/ivan-hc/Aisleriot-appimage if you need.

**Comment by joedefen** [comment]
- Thanks. You need not defend your decisions ... what you provide is great.
- I'll look at your links to successes and try to learn enuf to do one right. I've built appimages with https://github.com/AppImageCrafters/appimage-builder, but ArchImage looked easier ;-)
- I do think a "wishlist" for contributors would be nice (for apps wanted or in progress or currently thought to be impractical/impossible) not for your todo list. 
- However, I don't fully understand your organization or procedures for contributing (if even allowed), but if there is a page for contributions, I've missed it.

Cheers

**Comment by ivan-hc** [comment]
Archimage is a quite new method to bundle AppImages, so it is difficult to understand quickly.

Normally if I have a serious diffucults I pin issues needing help (for now it is only the hardware accelleration support).

All improvements come from issues and bug reports. I'll add a contributing when the project is a bit more mature. For now it is stil an experimental approach, sinche we are unable to made AppImages 100% compatible (for example) ins systems with Nvidia proprietary drivers (like the mine, some games or programs require Nouveau enabled).

**Comment by joedefen** [comment]
Looks the same to me.   I tried via appman and a direct download from releases and both behave the same.  Bummer.  But, not the end of the world issue ;-)
